#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

// Expose random functionality for testing. Could also be used as a library, but obviously not callable by AI unless it can build and run C code.

typedef enum : uint8_t
{
    AIRandom_D4 = 0,    // [1,4]
    AIRandom_D6,        // [1,6]
    AIRandom_D8,        // [1,8]
    AIRandom_D10,       // [1,10]
    AIRandom_D12,       // [1,12]
    AIRandom_D20,       // [1,20]
    AIRandom_D100,      // [1,100]
    AIRandom_D500       // [1,500]  probably not very popular.
}AIRandom_DieType;

// factorization of dice for least common multiple.
// This is the size of the table required to completely uniformly represent each possible die result for all the dice indicated.
//
// die  factors cumulative least common multiple
//  4:  2x2     2x2
//  6:  2x3     2x2x3
//  8:  2x2x2   2x2x2x3
// 10:  2x5     2x2x2x3x5
// 12:  2x2x3   2x2x2x3x5
// 20:  2x2x5   2x2x2x3x5
//100:  2x2x5x5 2x2x2x3x5x5 = (8*3*25) = 600
#define AIRANDOM_TABLE_SIZE 600


typedef struct
{
    uint32_t result;    // [1,N] for die with N sides.
    uint32_t index;     // [1,500]
}AIRandom_DieRoll;

/*! @abstract Roll a uniformly distributed pseudorandom die
 *  @param  type        The type of the die
 *  @return   The die roll */
extern AIRandom_DieRoll AIRandom_RollDie( AIRandom_DieType type );

/*! @abstract Returns true of the die roll was generated by this table (probably -- could be lucky)
 * @param allegedRoll       The roll alleged to have come from this table
 * @param type                      The type of die used
 * @return true if correct, false if fraudulent. */
extern bool AIRandom_AuditRoll( AIRandom_DieRoll allegedRoll,  AIRandom_DieType type );


/*! @abstract Print the Die table for use as raw markdown */
extern void AIRandom_PrintDieTable( FILE * /* nonnull*/ where );
